from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:
    from .generate_bindings import dependency_order, header_include, normalize_type, qualified_name
except ImportError:
    from generate_bindings import dependency_order, header_include, normalize_type, qualified_name


def python_module(namespace: str) -> str:
    if namespace.startswith("unitree_go::"):
        return "unitree_sdk2_cpp.idl.go2"
    if namespace.startswith("unitree_hg_doubleimu::"):
        return "unitree_sdk2_cpp.idl.hg_doubleimu"
    if namespace.startswith("unitree_hg::"):
        return "unitree_sdk2_cpp.idl.hg"
    return "unitree_sdk2_cpp.idl.ros2"


def generate(inventory: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    sdk_root = Path(inventory["sdk_root"])
    classes = list(inventory["classes"])
    known_classes = {normalize_type(qualified_name(item)) for item in classes}
    classes = dependency_order(classes, known_classes)
    includes = sorted({header_include(item, sdk_root) for item in classes})

    lines = [
        "// Generated by generator/generate_channel_registry.py. Do not edit manually.",
        '#include "channel/channels.hpp"',
        "",
    ]
    lines.extend(f"#include <{header}>" for header in includes)
    lines.extend(
        [
            "",
            "namespace unitree_sdk2_binding {",
            "",
            "void RegisterGeneratedChannelTypes(ChannelTypeRegistry &registry) {",
        ]
    )
    for item in classes:
        cpp_name = qualified_name(item)
        python_name = item["name"].removesuffix("_")
        full_python_name = f"{python_module(item['namespace'])}.{python_name}"
        lines.append(f'    registry.add<{cpp_name}>("{full_python_name}");')
    lines.extend(["}", "", "}  // namespace unitree_sdk2_binding", ""])
    return "\n".join(lines), {
        "schema_version": 1,
        "registered_types": [qualified_name(item) for item in classes],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate DDS channel type registry")
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--report", type=Path, required=True)
    arguments = parser.parse_args()
    source, report = generate(
        json.loads(arguments.inventory.read_text(encoding="utf-8"))
    )
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(source, encoding="utf-8")
    arguments.report.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"Registered {len(report['registered_types'])} DDS message types")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
