"""Generated DDS message bindings."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any

class AudioData:
    def __init__(self) -> None: ...
    @property
    def time_frame(self) -> int: ...
    @time_frame.setter
    def time_frame(self, value: int) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BmsCmd:
    def __init__(self) -> None: ...
    @property
    def off(self) -> int: ...
    @off.setter
    def off(self, value: int) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BmsState:
    def __init__(self) -> None: ...
    @property
    def version_high(self) -> int: ...
    @version_high.setter
    def version_high(self, value: int) -> None: ...
    @property
    def version_low(self) -> int: ...
    @version_low.setter
    def version_low(self, value: int) -> None: ...
    @property
    def status(self) -> int: ...
    @status.setter
    def status(self, value: int) -> None: ...
    @property
    def soc(self) -> int: ...
    @soc.setter
    def soc(self, value: int) -> None: ...
    @property
    def current(self) -> int: ...
    @current.setter
    def current(self, value: int) -> None: ...
    @property
    def cycle(self) -> int: ...
    @cycle.setter
    def cycle(self, value: int) -> None: ...
    @property
    def bq_ntc(self) -> list[int]: ...
    @bq_ntc.setter
    def bq_ntc(self, value: Sequence[int]) -> None: ...
    @property
    def mcu_ntc(self) -> list[int]: ...
    @mcu_ntc.setter
    def mcu_ntc(self, value: Sequence[int]) -> None: ...
    @property
    def cell_vol(self) -> list[int]: ...
    @cell_vol.setter
    def cell_vol(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class ConfigChangeStatus:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def content(self) -> str: ...
    @content.setter
    def content(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Error:
    def __init__(self) -> None: ...
    @property
    def source(self) -> int: ...
    @source.setter
    def source(self, value: int) -> None: ...
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Go2FrontVideoData:
    def __init__(self) -> None: ...
    @property
    def time_frame(self) -> int: ...
    @time_frame.setter
    def time_frame(self, value: int) -> None: ...
    @property
    def video720p(self) -> list[int]: ...
    @video720p.setter
    def video720p(self, value: Sequence[int]) -> None: ...
    @property
    def video360p(self) -> list[int]: ...
    @video360p.setter
    def video360p(self, value: Sequence[int]) -> None: ...
    @property
    def video180p(self) -> list[int]: ...
    @video180p.setter
    def video180p(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HeightMap:
    def __init__(self) -> None: ...
    @property
    def stamp(self) -> float: ...
    @stamp.setter
    def stamp(self, value: float) -> None: ...
    @property
    def frame_id(self) -> str: ...
    @frame_id.setter
    def frame_id(self, value: str) -> None: ...
    @property
    def resolution(self) -> float: ...
    @resolution.setter
    def resolution(self, value: float) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @origin.setter
    def origin(self, value: Sequence[float]) -> None: ...
    @property
    def data(self) -> list[float]: ...
    @data.setter
    def data(self, value: Sequence[float]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class IMUState:
    def __init__(self) -> None: ...
    @property
    def quaternion(self) -> list[float]: ...
    @quaternion.setter
    def quaternion(self, value: Sequence[float]) -> None: ...
    @property
    def gyroscope(self) -> list[float]: ...
    @gyroscope.setter
    def gyroscope(self, value: Sequence[float]) -> None: ...
    @property
    def accelerometer(self) -> list[float]: ...
    @accelerometer.setter
    def accelerometer(self, value: Sequence[float]) -> None: ...
    @property
    def rpy(self) -> list[float]: ...
    @rpy.setter
    def rpy(self, value: Sequence[float]) -> None: ...
    @property
    def temperature(self) -> int: ...
    @temperature.setter
    def temperature(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class InterfaceConfig:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @value.setter
    def value(self, value: int) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class LidarState:
    def __init__(self) -> None: ...
    @property
    def stamp(self) -> float: ...
    @stamp.setter
    def stamp(self, value: float) -> None: ...
    @property
    def firmware_version(self) -> str: ...
    @firmware_version.setter
    def firmware_version(self, value: str) -> None: ...
    @property
    def software_version(self) -> str: ...
    @software_version.setter
    def software_version(self, value: str) -> None: ...
    @property
    def sdk_version(self) -> str: ...
    @sdk_version.setter
    def sdk_version(self, value: str) -> None: ...
    @property
    def sys_rotation_speed(self) -> float: ...
    @sys_rotation_speed.setter
    def sys_rotation_speed(self, value: float) -> None: ...
    @property
    def com_rotation_speed(self) -> float: ...
    @com_rotation_speed.setter
    def com_rotation_speed(self, value: float) -> None: ...
    @property
    def error_state(self) -> int: ...
    @error_state.setter
    def error_state(self, value: int) -> None: ...
    @property
    def dirty_percentage(self) -> int: ...
    @dirty_percentage.setter
    def dirty_percentage(self, value: int) -> None: ...
    @property
    def cloud_frequency(self) -> float: ...
    @cloud_frequency.setter
    def cloud_frequency(self, value: float) -> None: ...
    @property
    def cloud_packet_loss_rate(self) -> float: ...
    @cloud_packet_loss_rate.setter
    def cloud_packet_loss_rate(self, value: float) -> None: ...
    @property
    def cloud_size(self) -> int: ...
    @cloud_size.setter
    def cloud_size(self, value: int) -> None: ...
    @property
    def cloud_scan_num(self) -> int: ...
    @cloud_scan_num.setter
    def cloud_scan_num(self, value: int) -> None: ...
    @property
    def imu_frequency(self) -> float: ...
    @imu_frequency.setter
    def imu_frequency(self, value: float) -> None: ...
    @property
    def imu_packet_loss_rate(self) -> float: ...
    @imu_packet_loss_rate.setter
    def imu_packet_loss_rate(self, value: float) -> None: ...
    @property
    def imu_rpy(self) -> list[float]: ...
    @imu_rpy.setter
    def imu_rpy(self, value: Sequence[float]) -> None: ...
    @property
    def serial_recv_stamp(self) -> float: ...
    @serial_recv_stamp.setter
    def serial_recv_stamp(self, value: float) -> None: ...
    @property
    def serial_buffer_size(self) -> int: ...
    @serial_buffer_size.setter
    def serial_buffer_size(self, value: int) -> None: ...
    @property
    def serial_buffer_read(self) -> int: ...
    @serial_buffer_read.setter
    def serial_buffer_read(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorCmd:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def q(self) -> float: ...
    @q.setter
    def q(self, value: float) -> None: ...
    @property
    def dq(self) -> float: ...
    @dq.setter
    def dq(self, value: float) -> None: ...
    @property
    def tau(self) -> float: ...
    @tau.setter
    def tau(self, value: float) -> None: ...
    @property
    def kp(self) -> float: ...
    @kp.setter
    def kp(self, value: float) -> None: ...
    @property
    def kd(self) -> float: ...
    @kd.setter
    def kd(self, value: float) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class LowCmd:
    def __init__(self) -> None: ...
    @property
    def head(self) -> list[int]: ...
    @head.setter
    def head(self, value: Sequence[int]) -> None: ...
    @property
    def level_flag(self) -> int: ...
    @level_flag.setter
    def level_flag(self, value: int) -> None: ...
    @property
    def frame_reserve(self) -> int: ...
    @frame_reserve.setter
    def frame_reserve(self, value: int) -> None: ...
    @property
    def sn(self) -> list[int]: ...
    @sn.setter
    def sn(self, value: Sequence[int]) -> None: ...
    @property
    def version(self) -> list[int]: ...
    @version.setter
    def version(self, value: Sequence[int]) -> None: ...
    @property
    def bandwidth(self) -> int: ...
    @bandwidth.setter
    def bandwidth(self, value: int) -> None: ...
    @property
    def motor_cmd(self) -> list[MotorCmd]: ...
    @motor_cmd.setter
    def motor_cmd(self, value: Sequence[MotorCmd]) -> None: ...
    @property
    def bms_cmd(self) -> BmsCmd: ...
    @bms_cmd.setter
    def bms_cmd(self, value: BmsCmd) -> None: ...
    @property
    def wireless_remote(self) -> list[int]: ...
    @wireless_remote.setter
    def wireless_remote(self, value: Sequence[int]) -> None: ...
    @property
    def led(self) -> list[int]: ...
    @led.setter
    def led(self, value: Sequence[int]) -> None: ...
    @property
    def fan(self) -> list[int]: ...
    @fan.setter
    def fan(self, value: Sequence[int]) -> None: ...
    @property
    def gpio(self) -> int: ...
    @gpio.setter
    def gpio(self, value: int) -> None: ...
    @property
    def reserve(self) -> int: ...
    @reserve.setter
    def reserve(self, value: int) -> None: ...
    @property
    def crc(self) -> int: ...
    @crc.setter
    def crc(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorState:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def q(self) -> float: ...
    @q.setter
    def q(self, value: float) -> None: ...
    @property
    def dq(self) -> float: ...
    @dq.setter
    def dq(self, value: float) -> None: ...
    @property
    def ddq(self) -> float: ...
    @ddq.setter
    def ddq(self, value: float) -> None: ...
    @property
    def tau_est(self) -> float: ...
    @tau_est.setter
    def tau_est(self, value: float) -> None: ...
    @property
    def q_raw(self) -> float: ...
    @q_raw.setter
    def q_raw(self, value: float) -> None: ...
    @property
    def dq_raw(self) -> float: ...
    @dq_raw.setter
    def dq_raw(self, value: float) -> None: ...
    @property
    def ddq_raw(self) -> float: ...
    @ddq_raw.setter
    def ddq_raw(self, value: float) -> None: ...
    @property
    def temperature(self) -> int: ...
    @temperature.setter
    def temperature(self, value: int) -> None: ...
    @property
    def lost(self) -> int: ...
    @lost.setter
    def lost(self, value: int) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class LowState:
    def __init__(self) -> None: ...
    @property
    def head(self) -> list[int]: ...
    @head.setter
    def head(self, value: Sequence[int]) -> None: ...
    @property
    def level_flag(self) -> int: ...
    @level_flag.setter
    def level_flag(self, value: int) -> None: ...
    @property
    def frame_reserve(self) -> int: ...
    @frame_reserve.setter
    def frame_reserve(self, value: int) -> None: ...
    @property
    def sn(self) -> list[int]: ...
    @sn.setter
    def sn(self, value: Sequence[int]) -> None: ...
    @property
    def version(self) -> list[int]: ...
    @version.setter
    def version(self, value: Sequence[int]) -> None: ...
    @property
    def bandwidth(self) -> int: ...
    @bandwidth.setter
    def bandwidth(self, value: int) -> None: ...
    @property
    def imu_state(self) -> IMUState: ...
    @imu_state.setter
    def imu_state(self, value: IMUState) -> None: ...
    @property
    def motor_state(self) -> list[MotorState]: ...
    @motor_state.setter
    def motor_state(self, value: Sequence[MotorState]) -> None: ...
    @property
    def bms_state(self) -> BmsState: ...
    @bms_state.setter
    def bms_state(self, value: BmsState) -> None: ...
    @property
    def foot_force(self) -> list[int]: ...
    @foot_force.setter
    def foot_force(self, value: Sequence[int]) -> None: ...
    @property
    def foot_force_est(self) -> list[int]: ...
    @foot_force_est.setter
    def foot_force_est(self, value: Sequence[int]) -> None: ...
    @property
    def tick(self) -> int: ...
    @tick.setter
    def tick(self, value: int) -> None: ...
    @property
    def wireless_remote(self) -> list[int]: ...
    @wireless_remote.setter
    def wireless_remote(self, value: Sequence[int]) -> None: ...
    @property
    def bit_flag(self) -> int: ...
    @bit_flag.setter
    def bit_flag(self, value: int) -> None: ...
    @property
    def adc_reel(self) -> float: ...
    @adc_reel.setter
    def adc_reel(self, value: float) -> None: ...
    @property
    def temperature_ntc1(self) -> int: ...
    @temperature_ntc1.setter
    def temperature_ntc1(self, value: int) -> None: ...
    @property
    def temperature_ntc2(self) -> int: ...
    @temperature_ntc2.setter
    def temperature_ntc2(self, value: int) -> None: ...
    @property
    def power_v(self) -> float: ...
    @power_v.setter
    def power_v(self, value: float) -> None: ...
    @property
    def power_a(self) -> float: ...
    @power_a.setter
    def power_a(self, value: float) -> None: ...
    @property
    def fan_frequency(self) -> list[int]: ...
    @fan_frequency.setter
    def fan_frequency(self, value: Sequence[int]) -> None: ...
    @property
    def reserve(self) -> int: ...
    @reserve.setter
    def reserve(self, value: int) -> None: ...
    @property
    def crc(self) -> int: ...
    @crc.setter
    def crc(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorCmds:
    def __init__(self) -> None: ...
    @property
    def cmds(self) -> list[MotorCmd]: ...
    @cmds.setter
    def cmds(self, value: Sequence[MotorCmd]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorStates:
    def __init__(self) -> None: ...
    @property
    def states(self) -> list[MotorState]: ...
    @states.setter
    def states(self, value: Sequence[MotorState]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PathPoint:
    def __init__(self) -> None: ...
    @property
    def t_from_start(self) -> float: ...
    @t_from_start.setter
    def t_from_start(self, value: float) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def yaw(self) -> float: ...
    @yaw.setter
    def yaw(self, value: float) -> None: ...
    @property
    def vx(self) -> float: ...
    @vx.setter
    def vx(self, value: float) -> None: ...
    @property
    def vy(self) -> float: ...
    @vy.setter
    def vy(self, value: float) -> None: ...
    @property
    def vyaw(self) -> float: ...
    @vyaw.setter
    def vyaw(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Req:
    def __init__(self) -> None: ...
    @property
    def uuid(self) -> str: ...
    @uuid.setter
    def uuid(self, value: str) -> None: ...
    @property
    def body(self) -> str: ...
    @body.setter
    def body(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Res:
    def __init__(self) -> None: ...
    @property
    def uuid(self) -> str: ...
    @uuid.setter
    def uuid(self, value: str) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: Sequence[int]) -> None: ...
    @property
    def body(self) -> str: ...
    @body.setter
    def body(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class SportModeCmd:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def gait_type(self) -> int: ...
    @gait_type.setter
    def gait_type(self, value: int) -> None: ...
    @property
    def speed_level(self) -> int: ...
    @speed_level.setter
    def speed_level(self, value: int) -> None: ...
    @property
    def foot_raise_height(self) -> float: ...
    @foot_raise_height.setter
    def foot_raise_height(self, value: float) -> None: ...
    @property
    def body_height(self) -> float: ...
    @body_height.setter
    def body_height(self, value: float) -> None: ...
    @property
    def position(self) -> list[float]: ...
    @position.setter
    def position(self, value: Sequence[float]) -> None: ...
    @property
    def euler(self) -> list[float]: ...
    @euler.setter
    def euler(self, value: Sequence[float]) -> None: ...
    @property
    def velocity(self) -> list[float]: ...
    @velocity.setter
    def velocity(self, value: Sequence[float]) -> None: ...
    @property
    def yaw_speed(self) -> float: ...
    @yaw_speed.setter
    def yaw_speed(self, value: float) -> None: ...
    @property
    def bms_cmd(self) -> BmsCmd: ...
    @bms_cmd.setter
    def bms_cmd(self, value: BmsCmd) -> None: ...
    @property
    def path_point(self) -> list[PathPoint]: ...
    @path_point.setter
    def path_point(self, value: Sequence[PathPoint]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class TimeSpec:
    def __init__(self) -> None: ...
    @property
    def sec(self) -> int: ...
    @sec.setter
    def sec(self, value: int) -> None: ...
    @property
    def nanosec(self) -> int: ...
    @nanosec.setter
    def nanosec(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class SportModeState:
    def __init__(self) -> None: ...
    @property
    def stamp(self) -> TimeSpec: ...
    @stamp.setter
    def stamp(self, value: TimeSpec) -> None: ...
    @property
    def error_code(self) -> int: ...
    @error_code.setter
    def error_code(self, value: int) -> None: ...
    @property
    def imu_state(self) -> IMUState: ...
    @imu_state.setter
    def imu_state(self, value: IMUState) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def progress(self) -> float: ...
    @progress.setter
    def progress(self, value: float) -> None: ...
    @property
    def gait_type(self) -> int: ...
    @gait_type.setter
    def gait_type(self, value: int) -> None: ...
    @property
    def foot_raise_height(self) -> float: ...
    @foot_raise_height.setter
    def foot_raise_height(self, value: float) -> None: ...
    @property
    def position(self) -> list[float]: ...
    @position.setter
    def position(self, value: Sequence[float]) -> None: ...
    @property
    def body_height(self) -> float: ...
    @body_height.setter
    def body_height(self, value: float) -> None: ...
    @property
    def velocity(self) -> list[float]: ...
    @velocity.setter
    def velocity(self, value: Sequence[float]) -> None: ...
    @property
    def yaw_speed(self) -> float: ...
    @yaw_speed.setter
    def yaw_speed(self, value: float) -> None: ...
    @property
    def range_obstacle(self) -> list[float]: ...
    @range_obstacle.setter
    def range_obstacle(self, value: Sequence[float]) -> None: ...
    @property
    def foot_force(self) -> list[int]: ...
    @foot_force.setter
    def foot_force(self, value: Sequence[int]) -> None: ...
    @property
    def foot_position_body(self) -> list[float]: ...
    @foot_position_body.setter
    def foot_position_body(self, value: Sequence[float]) -> None: ...
    @property
    def foot_speed_body(self) -> list[float]: ...
    @foot_speed_body.setter
    def foot_speed_body(self, value: Sequence[float]) -> None: ...
    @property
    def path_point(self) -> list[PathPoint]: ...
    @path_point.setter
    def path_point(self, value: Sequence[PathPoint]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class UwbState:
    def __init__(self) -> None: ...
    @property
    def version(self) -> list[int]: ...
    @version.setter
    def version(self, value: Sequence[int]) -> None: ...
    @property
    def channel(self) -> int: ...
    @channel.setter
    def channel(self, value: int) -> None: ...
    @property
    def joy_mode(self) -> int: ...
    @joy_mode.setter
    def joy_mode(self, value: int) -> None: ...
    @property
    def orientation_est(self) -> float: ...
    @orientation_est.setter
    def orientation_est(self, value: float) -> None: ...
    @property
    def pitch_est(self) -> float: ...
    @pitch_est.setter
    def pitch_est(self, value: float) -> None: ...
    @property
    def distance_est(self) -> float: ...
    @distance_est.setter
    def distance_est(self, value: float) -> None: ...
    @property
    def yaw_est(self) -> float: ...
    @yaw_est.setter
    def yaw_est(self, value: float) -> None: ...
    @property
    def tag_roll(self) -> float: ...
    @tag_roll.setter
    def tag_roll(self, value: float) -> None: ...
    @property
    def tag_pitch(self) -> float: ...
    @tag_pitch.setter
    def tag_pitch(self, value: float) -> None: ...
    @property
    def tag_yaw(self) -> float: ...
    @tag_yaw.setter
    def tag_yaw(self, value: float) -> None: ...
    @property
    def base_roll(self) -> float: ...
    @base_roll.setter
    def base_roll(self, value: float) -> None: ...
    @property
    def base_pitch(self) -> float: ...
    @base_pitch.setter
    def base_pitch(self, value: float) -> None: ...
    @property
    def base_yaw(self) -> float: ...
    @base_yaw.setter
    def base_yaw(self, value: float) -> None: ...
    @property
    def joystick(self) -> list[float]: ...
    @joystick.setter
    def joystick(self, value: Sequence[float]) -> None: ...
    @property
    def error_state(self) -> int: ...
    @error_state.setter
    def error_state(self, value: int) -> None: ...
    @property
    def buttons(self) -> int: ...
    @buttons.setter
    def buttons(self, value: int) -> None: ...
    @property
    def enabled_from_app(self) -> int: ...
    @enabled_from_app.setter
    def enabled_from_app(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class UwbSwitch:
    def __init__(self) -> None: ...
    @property
    def enabled(self) -> int: ...
    @enabled.setter
    def enabled(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class VoxelMapCompressed:
    def __init__(self) -> None: ...
    @property
    def stamp(self) -> float: ...
    @stamp.setter
    def stamp(self, value: float) -> None: ...
    @property
    def frame_id(self) -> str: ...
    @frame_id.setter
    def frame_id(self, value: str) -> None: ...
    @property
    def resolution(self) -> float: ...
    @resolution.setter
    def resolution(self, value: float) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @origin.setter
    def origin(self, value: Sequence[float]) -> None: ...
    @property
    def width(self) -> list[int]: ...
    @width.setter
    def width(self, value: Sequence[int]) -> None: ...
    @property
    def src_size(self) -> int: ...
    @src_size.setter
    def src_size(self, value: int) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class WirelessController:
    def __init__(self) -> None: ...
    @property
    def lx(self) -> float: ...
    @lx.setter
    def lx(self, value: float) -> None: ...
    @property
    def ly(self) -> float: ...
    @ly.setter
    def ly(self, value: float) -> None: ...
    @property
    def rx(self) -> float: ...
    @rx.setter
    def rx(self, value: float) -> None: ...
    @property
    def ry(self) -> float: ...
    @ry.setter
    def ry(self, value: float) -> None: ...
    @property
    def keys(self) -> int: ...
    @keys.setter
    def keys(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
