"""Generated DDS message bindings."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any

class AgvBmsState:
    def __init__(self) -> None: ...
    @property
    def software_version(self) -> str: ...
    @software_version.setter
    def software_version(self, value: str) -> None: ...
    @property
    def battery_percentage(self) -> int: ...
    @battery_percentage.setter
    def battery_percentage(self, value: int) -> None: ...
    @property
    def current(self) -> int: ...
    @current.setter
    def current(self, value: int) -> None: ...
    @property
    def temperature(self) -> list[int]: ...
    @temperature.setter
    def temperature(self, value: Sequence[int]) -> None: ...
    @property
    def docking_status(self) -> str: ...
    @docking_status.setter
    def docking_status(self, value: str) -> None: ...
    @property
    def is_charging(self) -> bool: ...
    @is_charging.setter
    def is_charging(self, value: bool) -> None: ...
    @property
    def is_dc_connected(self) -> bool: ...
    @is_dc_connected.setter
    def is_dc_connected(self, value: bool) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BmsCmd:
    def __init__(self) -> None: ...
    @property
    def cmd(self) -> int: ...
    @cmd.setter
    def cmd(self, value: int) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class BmsState:
    def __init__(self) -> None: ...
    @property
    def version_high(self) -> int: ...
    @version_high.setter
    def version_high(self, value: int) -> None: ...
    @property
    def version_low(self) -> int: ...
    @version_low.setter
    def version_low(self, value: int) -> None: ...
    @property
    def fn(self) -> int: ...
    @fn.setter
    def fn(self, value: int) -> None: ...
    @property
    def cell_vol(self) -> list[int]: ...
    @cell_vol.setter
    def cell_vol(self, value: Sequence[int]) -> None: ...
    @property
    def bmsvoltage(self) -> list[int]: ...
    @bmsvoltage.setter
    def bmsvoltage(self, value: Sequence[int]) -> None: ...
    @property
    def current(self) -> int: ...
    @current.setter
    def current(self, value: int) -> None: ...
    @property
    def soc(self) -> int: ...
    @soc.setter
    def soc(self, value: int) -> None: ...
    @property
    def soh(self) -> int: ...
    @soh.setter
    def soh(self, value: int) -> None: ...
    @property
    def temperature(self) -> list[int]: ...
    @temperature.setter
    def temperature(self, value: Sequence[int]) -> None: ...
    @property
    def cycle(self) -> int: ...
    @cycle.setter
    def cycle(self, value: int) -> None: ...
    @property
    def manufacturer_date(self) -> int: ...
    @manufacturer_date.setter
    def manufacturer_date(self, value: int) -> None: ...
    @property
    def bmsstate(self) -> list[int]: ...
    @bmsstate.setter
    def bmsstate(self, value: Sequence[int]) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorCmd:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def q(self) -> float: ...
    @q.setter
    def q(self, value: float) -> None: ...
    @property
    def dq(self) -> float: ...
    @dq.setter
    def dq(self, value: float) -> None: ...
    @property
    def tau(self) -> float: ...
    @tau.setter
    def tau(self, value: float) -> None: ...
    @property
    def kp(self) -> float: ...
    @kp.setter
    def kp(self, value: float) -> None: ...
    @property
    def kd(self) -> float: ...
    @kd.setter
    def kd(self, value: float) -> None: ...
    @property
    def reserve(self) -> int: ...
    @reserve.setter
    def reserve(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HandCmd:
    def __init__(self) -> None: ...
    @property
    def motor_cmd(self) -> list[MotorCmd]: ...
    @motor_cmd.setter
    def motor_cmd(self, value: Sequence[MotorCmd]) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class IMUState:
    def __init__(self) -> None: ...
    @property
    def quaternion(self) -> list[float]: ...
    @quaternion.setter
    def quaternion(self, value: Sequence[float]) -> None: ...
    @property
    def gyroscope(self) -> list[float]: ...
    @gyroscope.setter
    def gyroscope(self, value: Sequence[float]) -> None: ...
    @property
    def accelerometer(self) -> list[float]: ...
    @accelerometer.setter
    def accelerometer(self, value: Sequence[float]) -> None: ...
    @property
    def rpy(self) -> list[float]: ...
    @rpy.setter
    def rpy(self, value: Sequence[float]) -> None: ...
    @property
    def temperature(self) -> int: ...
    @temperature.setter
    def temperature(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MotorState:
    def __init__(self) -> None: ...
    @property
    def mode(self) -> int: ...
    @mode.setter
    def mode(self, value: int) -> None: ...
    @property
    def q(self) -> float: ...
    @q.setter
    def q(self, value: float) -> None: ...
    @property
    def dq(self) -> float: ...
    @dq.setter
    def dq(self, value: float) -> None: ...
    @property
    def ddq(self) -> float: ...
    @ddq.setter
    def ddq(self, value: float) -> None: ...
    @property
    def tau_est(self) -> float: ...
    @tau_est.setter
    def tau_est(self, value: float) -> None: ...
    @property
    def temperature(self) -> list[int]: ...
    @temperature.setter
    def temperature(self, value: Sequence[int]) -> None: ...
    @property
    def vol(self) -> float: ...
    @vol.setter
    def vol(self, value: float) -> None: ...
    @property
    def sensor(self) -> list[int]: ...
    @sensor.setter
    def sensor(self, value: Sequence[int]) -> None: ...
    @property
    def motorstate(self) -> int: ...
    @motorstate.setter
    def motorstate(self, value: int) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PressSensorState:
    def __init__(self) -> None: ...
    @property
    def pressure(self) -> list[float]: ...
    @pressure.setter
    def pressure(self, value: Sequence[float]) -> None: ...
    @property
    def temperature(self) -> list[float]: ...
    @temperature.setter
    def temperature(self, value: Sequence[float]) -> None: ...
    @property
    def lost(self) -> int: ...
    @lost.setter
    def lost(self, value: int) -> None: ...
    @property
    def reserve(self) -> int: ...
    @reserve.setter
    def reserve(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class HandState:
    def __init__(self) -> None: ...
    @property
    def motor_state(self) -> list[MotorState]: ...
    @motor_state.setter
    def motor_state(self, value: Sequence[MotorState]) -> None: ...
    @property
    def press_sensor_state(self) -> list[PressSensorState]: ...
    @press_sensor_state.setter
    def press_sensor_state(self, value: Sequence[PressSensorState]) -> None: ...
    @property
    def imu_state(self) -> IMUState: ...
    @imu_state.setter
    def imu_state(self, value: IMUState) -> None: ...
    @property
    def power_v(self) -> float: ...
    @power_v.setter
    def power_v(self, value: float) -> None: ...
    @property
    def power_a(self) -> float: ...
    @power_a.setter
    def power_a(self, value: float) -> None: ...
    @property
    def system_v(self) -> float: ...
    @system_v.setter
    def system_v(self, value: float) -> None: ...
    @property
    def device_v(self) -> float: ...
    @device_v.setter
    def device_v(self, value: float) -> None: ...
    @property
    def error(self) -> list[int]: ...
    @error.setter
    def error(self, value: Sequence[int]) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class LowCmd:
    def __init__(self) -> None: ...
    @property
    def mode_pr(self) -> int: ...
    @mode_pr.setter
    def mode_pr(self, value: int) -> None: ...
    @property
    def mode_machine(self) -> int: ...
    @mode_machine.setter
    def mode_machine(self, value: int) -> None: ...
    @property
    def motor_cmd(self) -> list[MotorCmd]: ...
    @motor_cmd.setter
    def motor_cmd(self, value: Sequence[MotorCmd]) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    @property
    def crc(self) -> int: ...
    @crc.setter
    def crc(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class LowState:
    def __init__(self) -> None: ...
    @property
    def version(self) -> list[int]: ...
    @version.setter
    def version(self, value: Sequence[int]) -> None: ...
    @property
    def mode_pr(self) -> int: ...
    @mode_pr.setter
    def mode_pr(self, value: int) -> None: ...
    @property
    def mode_machine(self) -> int: ...
    @mode_machine.setter
    def mode_machine(self, value: int) -> None: ...
    @property
    def tick(self) -> int: ...
    @tick.setter
    def tick(self, value: int) -> None: ...
    @property
    def imu_state(self) -> IMUState: ...
    @imu_state.setter
    def imu_state(self, value: IMUState) -> None: ...
    @property
    def motor_state(self) -> list[MotorState]: ...
    @motor_state.setter
    def motor_state(self, value: Sequence[MotorState]) -> None: ...
    @property
    def wireless_remote(self) -> list[int]: ...
    @wireless_remote.setter
    def wireless_remote(self, value: Sequence[int]) -> None: ...
    @property
    def reserve(self) -> list[int]: ...
    @reserve.setter
    def reserve(self, value: Sequence[int]) -> None: ...
    @property
    def crc(self) -> int: ...
    @crc.setter
    def crc(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MainBoardState:
    def __init__(self) -> None: ...
    @property
    def fan_state(self) -> list[int]: ...
    @fan_state.setter
    def fan_state(self, value: Sequence[int]) -> None: ...
    @property
    def temperature(self) -> list[int]: ...
    @temperature.setter
    def temperature(self, value: Sequence[int]) -> None: ...
    @property
    def value(self) -> list[float]: ...
    @value.setter
    def value(self, value: Sequence[float]) -> None: ...
    @property
    def state(self) -> list[int]: ...
    @state.setter
    def state(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class SportModeState:
    def __init__(self) -> None: ...
    @property
    def fsm_id(self) -> int: ...
    @fsm_id.setter
    def fsm_id(self, value: int) -> None: ...
    @property
    def fsm_mode(self) -> int: ...
    @fsm_mode.setter
    def fsm_mode(self, value: int) -> None: ...
    @property
    def task_id(self) -> int: ...
    @task_id.setter
    def task_id(self, value: int) -> None: ...
    @property
    def task_time(self) -> float: ...
    @task_time.setter
    def task_time(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
