"""Generated DDS message bindings."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any

class doubleIMUState:
    def __init__(self) -> None: ...
    @property
    def quaternion(self) -> list[float]: ...
    @quaternion.setter
    def quaternion(self, value: Sequence[float]) -> None: ...
    @property
    def gyroscope(self) -> list[float]: ...
    @gyroscope.setter
    def gyroscope(self, value: Sequence[float]) -> None: ...
    @property
    def accelerometer(self) -> list[float]: ...
    @accelerometer.setter
    def accelerometer(self, value: Sequence[float]) -> None: ...
    @property
    def rpy(self) -> list[float]: ...
    @rpy.setter
    def rpy(self, value: Sequence[float]) -> None: ...
    @property
    def temperature(self) -> int: ...
    @temperature.setter
    def temperature(self, value: int) -> None: ...
    @property
    def tick(self) -> int: ...
    @tick.setter
    def tick(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
