"""Generated DDS message bindings."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any

class Time:
    def __init__(self) -> None: ...
    @property
    def sec(self) -> int: ...
    @sec.setter
    def sec(self, value: int) -> None: ...
    @property
    def nanosec(self) -> int: ...
    @nanosec.setter
    def nanosec(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Header:
    def __init__(self) -> None: ...
    @property
    def stamp(self) -> Any: ...
    @stamp.setter
    def stamp(self, value: Any) -> None: ...
    @property
    def frame_id(self) -> str: ...
    @frame_id.setter
    def frame_id(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Quaternion:
    def __init__(self) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    @property
    def w(self) -> float: ...
    @w.setter
    def w(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Vector3:
    def __init__(self) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Imu:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def orientation(self) -> Any: ...
    @orientation.setter
    def orientation(self, value: Any) -> None: ...
    @property
    def orientation_covariance(self) -> list[float]: ...
    @orientation_covariance.setter
    def orientation_covariance(self, value: Sequence[float]) -> None: ...
    @property
    def angular_velocity(self) -> Any: ...
    @angular_velocity.setter
    def angular_velocity(self, value: Any) -> None: ...
    @property
    def angular_velocity_covariance(self) -> list[float]: ...
    @angular_velocity_covariance.setter
    def angular_velocity_covariance(self, value: Sequence[float]) -> None: ...
    @property
    def linear_acceleration(self) -> Any: ...
    @linear_acceleration.setter
    def linear_acceleration(self, value: Any) -> None: ...
    @property
    def linear_acceleration_covariance(self) -> list[float]: ...
    @linear_acceleration_covariance.setter
    def linear_acceleration_covariance(self, value: Sequence[float]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Point:
    def __init__(self) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Pose:
    def __init__(self) -> None: ...
    @property
    def position(self) -> Point: ...
    @position.setter
    def position(self, value: Point) -> None: ...
    @property
    def orientation(self) -> Quaternion: ...
    @orientation.setter
    def orientation(self, value: Quaternion) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class MapMetaData:
    def __init__(self) -> None: ...
    @property
    def map_load_time(self) -> Any: ...
    @map_load_time.setter
    def map_load_time(self, value: Any) -> None: ...
    @property
    def resolution(self) -> float: ...
    @resolution.setter
    def resolution(self, value: float) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def origin(self) -> Any: ...
    @origin.setter
    def origin(self, value: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class OccupancyGrid:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def info(self) -> MapMetaData: ...
    @info.setter
    def info(self, value: MapMetaData) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: Sequence[int]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PoseWithCovariance:
    def __init__(self) -> None: ...
    @property
    def pose(self) -> Pose: ...
    @pose.setter
    def pose(self, value: Pose) -> None: ...
    @property
    def covariance(self) -> list[float]: ...
    @covariance.setter
    def covariance(self, value: Sequence[float]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Twist:
    def __init__(self) -> None: ...
    @property
    def linear(self) -> Vector3: ...
    @linear.setter
    def linear(self, value: Vector3) -> None: ...
    @property
    def angular(self) -> Vector3: ...
    @angular.setter
    def angular(self, value: Vector3) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class TwistWithCovariance:
    def __init__(self) -> None: ...
    @property
    def twist(self) -> Twist: ...
    @twist.setter
    def twist(self, value: Twist) -> None: ...
    @property
    def covariance(self) -> list[float]: ...
    @covariance.setter
    def covariance(self, value: Sequence[float]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Odometry:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def child_frame_id(self) -> str: ...
    @child_frame_id.setter
    def child_frame_id(self, value: str) -> None: ...
    @property
    def pose(self) -> Any: ...
    @pose.setter
    def pose(self, value: Any) -> None: ...
    @property
    def twist(self) -> Any: ...
    @twist.setter
    def twist(self, value: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Point32:
    def __init__(self) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PointField:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, value: int) -> None: ...
    @property
    def datatype(self) -> int: ...
    @datatype.setter
    def datatype(self, value: int) -> None: ...
    @property
    def count(self) -> int: ...
    @count.setter
    def count(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PointCloud2:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def fields(self) -> list[PointField]: ...
    @fields.setter
    def fields(self, value: Sequence[PointField]) -> None: ...
    @property
    def is_bigendian(self) -> bool: ...
    @is_bigendian.setter
    def is_bigendian(self, value: bool) -> None: ...
    @property
    def point_step(self) -> int: ...
    @point_step.setter
    def point_step(self, value: int) -> None: ...
    @property
    def row_step(self) -> int: ...
    @row_step.setter
    def row_step(self, value: int) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: Sequence[int]) -> None: ...
    @property
    def is_dense(self) -> bool: ...
    @is_dense.setter
    def is_dense(self, value: bool) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PointStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def point(self) -> Point: ...
    @point.setter
    def point(self, value: Point) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class Pose2D:
    def __init__(self) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def theta(self) -> float: ...
    @theta.setter
    def theta(self, value: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PoseStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def pose(self) -> Pose: ...
    @pose.setter
    def pose(self, value: Pose) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class PoseWithCovarianceStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def pose(self) -> PoseWithCovariance: ...
    @pose.setter
    def pose(self, value: PoseWithCovariance) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QuaternionStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def quaternion(self) -> Quaternion: ...
    @quaternion.setter
    def quaternion(self, value: Quaternion) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class String:
    def __init__(self) -> None: ...
    @property
    def data(self) -> str: ...
    @data.setter
    def data(self, value: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class TwistStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def twist(self) -> Twist: ...
    @twist.setter
    def twist(self, value: Twist) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class TwistWithCovarianceStamped:
    def __init__(self) -> None: ...
    @property
    def header(self) -> Any: ...
    @header.setter
    def header(self, value: Any) -> None: ...
    @property
    def twist(self) -> TwistWithCovariance: ...
    @twist.setter
    def twist(self, value: TwistWithCovariance) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
