"""Unitree SDK2 extension API signature preview."""
from . import channel as channel
from . import idl as idl
from . import robot as robot

__all__ = ["channel", "idl", "robot", "OsHelper"]

class OsHelper:
    @staticmethod
    def instance() -> OsHelper: ...
    def get_uid(self) -> int: ...
    def get_gid(self) -> int: ...
    def get_user(self) -> str: ...
    def get_processor_number(self) -> int: ...
    def get_page_size(self) -> int: ...
    def get_hostname(self) -> str: ...
