"""Typed CycloneDDS channel API."""
from collections.abc import Callable
from typing import Any, Generic, TypeVar

MessageT = TypeVar("MessageT")

def registered_message_types() -> list[str]: ...
def initialize(domain_id: int = 0, network_interface: str = "") -> None: ...
def initialize_from_config(config_file: str = "") -> None: ...
def release() -> None: ...

class ChannelPublisher(Generic[MessageT]):
    def __init__(self, topic: str, message_type: type[MessageT]) -> None: ...
    @property
    def topic(self) -> str: ...
    @property
    def message_type_name(self) -> str: ...
    def init_channel(self) -> None: ...
    def close_channel(self) -> None: ...
    def write(self, message: MessageT, wait_microsec: int = 0) -> bool: ...

class ChannelSubscriber(Generic[MessageT]):
    def __init__(
        self,
        topic: str,
        message_type: type[MessageT],
        callback: Callable[[MessageT], None],
        queue_length: int = 0,
    ) -> None: ...
    @property
    def topic(self) -> str: ...
    @property
    def message_type_name(self) -> str: ...
    @property
    def last_data_available_time(self) -> int: ...
    def init_channel(self) -> None: ...
    def close_channel(self) -> None: ...
